### ISSUE TITLE
eclipse 2019-12 install failed

### ISSUE THREAD

**Issue by egolearner** [d-akara/eclipse-plugin-commander#48]
With following error messages:

> Cannot complete the install because one or more required items could not be found.
Software currently installed: Commander Feature 1.4.0 (dakara.eclipse.commander.feature.feature.group 1.4.0)
Missing requirement: Commander 1.4.0.202002211146 (dakara.eclipse.commander.plugin 1.4.0.202002211146) requires 'osgi.bundle; org.junit 0.0.0' but it could not be found
Cannot satisfy dependency:
From: Commander Feature 1.4.0 (dakara.eclipse.commander.feature.feature.group 1.4.0)
To: org.eclipse.equinox.p2.iu; dakara.eclipse.commander.plugin [1.4.0.202002211146,1.4.0.202002211146]

**Comment by d-akara** [comment]
Try the solution from here and let me know if works for you
https://github.com/dakaraphi/eclipse-plugin-commander/issues/39#issuecomment-370978459

**Comment by egolearner** [comment]
After installing "Eclipse Test Framework" from update site, I successfully installed your plugin.
Thanks.
